version: "3.9"
services:
  postgres-general:
    build:
      context: ./postgres
      dockerfile: postgres-general.Dockerfile
    container_name: postgres-general
    ports:
      - "5432:5432"
    volumes:
      - postgres-general:/var/lib/postgresql/data
    env_file:
      - mw-general/.env
    networks:
      - app-network

  # mw-general
  mw-general:
    build:
      context: ./mw-general
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres-general
    networks:
      - app-network

  mw-general-bff:
    build:
      context: ./mw-general-bff
      dockerfile: Dockerfile
    ports:
      - "7995:7995"
    depends_on:
      - mw-general
    networks:
      - app-network

  postgres-chat:
    build:
      context: ./postgres
      dockerfile: postgres-chat.Dockerfile
    container_name: postgres-chat
    ports:
      - "5433:5432"
    volumes:
      - postgres-chat:/var/lib/postgresql/data
    env_file:
      - ./mw-chat/.env
    networks:
      - app-network

  mw-chat:
    build:
      context: ./mw-chat
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres-chat
    networks:
      - app-network

  mw-chat-bff:
    build:
      context: ./mw-chat-bff
      dockerfile: Dockerfile
    ports:
      - "7999:7999"
    depends_on:
      - mw-chat
    networks:
      - app-network

  mw-chat-websocket:
    build:
      context: ./mw-chat-websocket
      dockerfile: Dockerfile
    ports:
      - "7994:7994"
    depends_on:
      - mw-chat-bff
    networks:
      - app-network

  postgres-storage:
    build:
      context: ./postgres
      dockerfile: postgres-storage.Dockerfile
    container_name: postgres-storage
    ports:
      - "5435:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    env_file:
      - ./mw-storage/.env
    networks:
      - app-network

  mw-storage:
    build:
      context: ./mw-storage
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - postgres-storage
    networks:
      - app-network

  postgres-survey:
    build:
      context: ./postgres
      dockerfile: postgres-survey.Dockerfile
    container_name: postgres-survey
    ports:
      - "5436:5432"
    volumes:
      - postgres-survey:/var/lib/postgresql/data
    env_file:
      - ./mw-survey/.env
    networks:
      - app-network

  mw-survey:
    build:
      context: ./mw-survey
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - postgres-survey
    networks:
      - app-network

  postgres-notification:
    build:
      context: ./postgres
      dockerfile: postgres-notification.Dockerfile
    container_name: postgres-notification
    ports:
      - "5434:5432"
    volumes:
      - postgres-notification:/var/lib/postgresql/data
    env_file:
      - ./mw-notification/.env
    networks:
      - app-network

  mw-notification-bff:
    build:
      context: ./mw-notification-bff
      dockerfile: Dockerfile
    ports:
      - "7993:7993"
    depends_on:
      - mw-notification
    networks:
      - app-network

  mw-notification:
    build:
      context: ./mw-notification
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - postgres-notification
    networks:
      - app-network

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "9876:3000"
    env_file:
      - ./grafana/.env
    depends_on:
      - postgres-general
      - postgres-chat
      - postgres-storage
      - postgres-survey
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/mastersway.duckdns.org/privkey.pem:/etc/nginx/server.key:ro
      - /etc/letsencrypt/live/mastersway.duckdns.org/fullchain.pem:/etc/nginx/server.crt:ro
    depends_on:
      - mw-general
      - mw-chat
      - mw-chat-bff
      - mw-chat-websocket
      - mw-survey
      - mw-storage
    networks:
      - app-network

volumes:
  postgres-general:
  postgres-chat:
  postgres-storage:
  postgres-survey:
  postgres-notification:

networks:
  app-network:
    driver: host
