version: "3.9"
services:
  postgres-general:
    build:
      context: ./postgres
      dockerfile: postgres-general.Dockerfile
    container_name: postgres-general
    ports:
      - "5432:5432"
    volumes:
      - postgres-general:/var/lib/postgresql/data
    env_file:
      - ./mw-server/.env
    networks:
      - app-network

  postgres-chat:
    build:
      context: ./postgres
      dockerfile: postgres-chat.Dockerfile
    container_name: postgres-chat
    ports:
      - "5433:5432"
    volumes:
      - postgres-chat:/var/lib/postgresql/data
    env_file:
      - ./mw-chat/.env
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "5173:80"
    volumes:
      - ./gateway/local.nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

volumes:
  postgres-general:
  postgres-chat:

networks:
  app-network:
    driver: bridge
