version: "3.9"
services:
  postgres-general:
    build:
      context: ./postgres
      dockerfile: postgres-general.Dockerfile
    container_name: postgres-general
    ports:
      - "5432:5432"
    volumes:
      - postgres-general:/var/lib/postgresql/data
    env_file:
      - ./mw-server/.env
    networks:
      - app-network

  postgres-chat:
    build:
      context: ./postgres
      dockerfile: postgres-chat.Dockerfile
    container_name: postgres-chat
    ports:
      - "5433:5432"
    volumes:
      - postgres-chat:/var/lib/postgresql/data
    env_file:
      - ./mw-chat/.env
    networks:
      - app-network

  postgres-storage:
    build:
      context: ./postgres
      dockerfile: postgres-storage.Dockerfile
    container_name: postgres-storage
    ports:
      - "5435:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    env_file:
      - ./mw-storage/.env
    networks:
      - app-network

  postgres-survey:
    build:
      context: ./postgres
      dockerfile: postgres-survey.Dockerfile
    container_name: postgres-survey
    ports:
      - "5436:5432"
    volumes:
      - postgres-survey:/var/lib/postgresql/data
    env_file:
      - ./mw-survey/.env
    networks:
      - app-network

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "9876:3000"
    env_file:
      - ./grafana/.env
    depends_on:
      - postgres-general
      - postgres-chat
      - postgres-storage
      - postgres-survey
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "5173:80"
    volumes:
      - ./gateway/local.nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres-general:
  postgres-chat:
  postgres-storage:
  postgres-survey:

networks:
  app-network:
    driver: host
