version: "3.9"
services:
  postgres-general:
    build:
      context: ./postgres
      dockerfile: postgres-general.Dockerfile
    container_name: postgres-general
    ports:
      - "5432:5432"
    volumes:
      - postgres-general:/var/lib/postgresql/data
    env_file:
      - ./mw-server/.env
    networks:
      - app-network

  # mw-general
  mw-server:
    build:
      context: ./mw-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres-general
    networks:
      - app-network

  postgres-chat:
    build:
      context: ./postgres
      dockerfile: postgres-chat.Dockerfile
    container_name: postgres-chat
    ports:
      - "5433:5432"
    volumes:
      - postgres-chat:/var/lib/postgresql/data
    env_file:
      - ./mw-chat/.env
    networks:
      - app-network
  
  mw-chat:
    build:
      context: ./mw-chat
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres-chat
    networks:
      - app-network
  
  mw-chat-bff:
    build:
      context: ./mw-chat-bff
      dockerfile: Dockerfile
    ports:
      - "7999:7999"
    depends_on:
      - mw-chat
    networks:
      - app-network

  mw-chat-websocket:
    build:
      context: ./mw-chat-websocket
      dockerfile: Dockerfile
    ports:
      - "7994:7994"
    depends_on:
      - mw-chat-bff
    networks:
      - app-network

  mw-webapp:
    build:
      context: ./mw-webapp
      dockerfile: Dockerfile
    ports:
      - "5172:5174"
    networks:
      - app-network

  postgres-storage:
    build:
      context: ./postgres
      dockerfile: postgres-storage.Dockerfile
    container_name: postgres-storage
    ports:
      - "5435:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    env_file:
      - ./mw-storage/.env
    networks:
      - app-network

  mw-storage:
    build:
      context: ./mw-storage
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - postgres-storage
    networks:
      - app-network

  postgres-survey:
    build:
      context: ./postgres
      dockerfile: postgres-survey.Dockerfile
    container_name: postgres-survey
    ports:
      - "5436:5432"
    volumes:
      - postgres-survey:/var/lib/postgresql/data
    env_file:
      - ./mw-survey/.env
    networks:
      - app-network

  mw-survey:
    build:
      context: ./mw-survey
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - postgres-survey
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "5173:80"
    volumes:
      - ./gateway/local.docker.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mw-server
      - mw-webapp
      - mw-chat
      - mw-chat-bff
      - mw-chat-websocket
      - mw-storage
      - mw-survey
    networks:
      - app-network

volumes:
  postgres-general:
  postgres-chat:
  postgres-storage:
  postgres-survey:


networks:
  app-network:
    driver: bridge
