openapi: 3.0.1
info:
  contact: {}
  title: Masters way notification API
  version: "1.0"
servers:
- url: /notification
paths:
  /dev/reset-db:
    get:
      description: resets db
      responses:
        "204":
          content: {}
          description: No Content
      summary: resets db
      tags:
      - dev
  /list:
    get:
      operationId: get-notification-list
      responses:
        "204":
          content: {}
          description: No Content
      summary: Get notification list by user id
      tags:
      - notification
components:
  schemas: {}
x-original-swagger-version: "2.0"
